CREATE DATABASE IF NOT EXISTS andre_dupla;

USE andre_dupla;

CREATE TABLE IF NOT EXISTS Professores (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Aulas (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Sala VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Diario (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_Professor INT,
    ID_Aula INT,
    HoraAula TIME,
    FOREIGN KEY (ID_Professor) REFERENCES Professores(ID),
    FOREIGN KEY (ID_Aula) REFERENCES Aulas(ID)
);

